package com.awesheet.enums;

public enum FunctionType{
    ABS_FUNCTION_TYPE,
    COS_FUNCTION_TYPE,
    SIN_FUNCTION_TYPE,
    TAN_FUNCTION_TYPE,
    POW_FUNCTION_TYPE,
    SUM_FUNCTION_TYPE,
    MULT_FUNCTION_TYPE,
    LOG_FUNCTION_TYPE,
    LOG_10_FUNCTION_TYPE,
    AND_FUNCTION_TYPE,
    OR_FUNCTION_TYPE,
    NOT_FUNCTION_TYPE,
    XOR_FUNCTION_TYPE,
    MAX_FUNCTION_TYPE,
    MIN_FUNCTION_TYPE,
    MEAN_FUNCTION_TYPE,
    MEDIAN_FUNCTION_TYPE,
    STDDEV_FUNCTION_TYPE,
    CONCAT_FUNCTION_TYPE,
    INCLUDES_FUNCTION_TYPE,
    TRIM_FUNCTION_TYPE,
    REMOVE_FUNCTION_TYPE
}
